# KyFromAbove Explorer November Stats

This project takes data from an AWS Athena DataCatalog database table for the [KyFromAbove Open Data on AWS](https://registry.opendata.aws/kyfromabove/) from the [KyFromAbove Exploerer](https://explore.kyfromabove.ky.gov/) for the month of November.  For simplicity and security reasons, I performed the query in Athena and just exported the results to CSV.  This way, I'm not providing access to AWS, plus not having to query, paginate, and refresh a token.

```sql
    SELECT * FROM "s3_access_logs_db"."kyfromabove_monthly"
    WHERE "year" = '2024'
    AND "month" = '11';
```

## Project Questions

 - How many GET requests is the KyFromAbove S3 Bucket receiving from the KyFromAbove Explorer.
 - How many bytes are getting sent?
 - What are the most popular images?
 - Who is using the data?

___

## Read the data using pandas

In [1]:
import pandas as pd

In [2]:
# add my csv file path
csv_file = './97d9edc8-c0c4-4f42-b7b2-fe8c8e11ee8f.csv'

# read as a dataframe
logs = pd.read_csv(
    csv_file, 
    header=0, 
    dtype=
    {'httpstatus': str,  # columns 9 & 13 popped out as mixed Dtype
     'totaltime': str    # so I just assigned them as strings
    }
)

#### Drop columns

In [3]:
logs.columns

Index(['bucketowner', 'bucket_name', 'requestdatetime', 'remoteip',
       'requester', 'requestid', 'operation', 'key', 'request_uri',
       'httpstatus', 'errorcode', 'bytessent', 'objectsize', 'totaltime',
       'turnaroundtime', 'referrer', 'useragent', 'versionid', 'hostid',
       'sigv', 'ciphersuite', 'authtype', 'endpoint', 'tlsversion',
       'accesspointarn', 'aclrequired', 'year', 'month'],
      dtype='object')

Since I know that the values for `bucketowner` and `bucket_name` will be the same for all rows, I can drop those two.  Also, because this database table is partitioned based on `year` and`month`, I can drop these values.  

I also know that I'm looking for requests that come from the KyFromAbove Explorer, so I will also filter the dataframe for values `referrer=https://explore.kyfromabove.ky.gov/`

In [4]:
# drop bucketowner, bucket_name, year, and month
logs = logs.drop(['bucketowner', 'bucket_name', 'year', 'month'], axis=1)

# filter for the referrer
logs_filtered = logs[logs['referrer'] == '"https://explore.kyfromabove.ky.gov/"']

# print the head and tail to view table
print(f'The unfiltered dataset has this for it"s shape value: {logs.shape}\n')
print(f'The filtered dataset as a shape value of: {logs_filtered.shape}\n')  # just to get an idea of the data
logs_filtered

The unfiltered dataset has this for it"s shape value: (6612895, 24)

The filtered dataset as a shape value of: (1834294, 24)

,requestdatetime,remoteip,requester,requestid,operation,key,request_uri,httpstatus,errorcode,bytessent,...,useragent,versionid,hostid,sigv,ciphersuite,authtype,endpoint,tlsversion,accesspointarn,aclrequired
0,01/Nov/2024:14:51:04 +0000,162.211.36.0,-,DVH2XBFQTQEH3NJ2,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,-,65536.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,lcdV8enFq1pLpT8KROtZESUBqTO1++ZV6BHj8e7e1NHYO3...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
1,01/Nov/2024:14:51:04 +0000,162.211.36.0,-,DVH61VS2E85ZB0R4,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,-,113170.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,goZTYKtuX8o/S150TnCwmYWWXx7LEiYtGzVr9I78bshw4T...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
2,01/Nov/2024:14:51:04 +0000,162.211.36.0,-,DVHA123N17KNX3H6,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,-,196.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,K1pddESQp0nqAgTcP+ecpft6eYuaGwVvhwEiKcT8/YakpE...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
3,01/Nov/2024:14:51:05 +0000,162.211.36.0,-,BX6PD6E7GYYVTE57,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,-,195.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,iajZzD+oObLS1bSOiYvLcUQ2/7DbAPQExi7n3BgaIqCAyK...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
14,01/Nov/2024:15:11:51 +0000,65.34.46.11,-,W0C27ZNMP1SGM8TY,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season2...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",200,-,82086.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,QW9g6pLQM/iDerpyot2zUaZqZz6z3M7yqAVMvHmR6uDCjI...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6612058,30/Nov/2024:18:39:55 +0000,76.35.248.15,-,GNTNA6KN6D3MDG34,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",206,-,65536.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,EpRv8VbDo4W8b5hcelIHfHWskvBNMtf8paVTHDHvldYU5y...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
6612059,30/Nov/2024:18:39:56 +0000,76.35.248.15,-,MSCXY8PW66XSPZHQ,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",206,-,121223.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,Q2MZG7wO5oCptGKPP/e7dpYghBT/k5nCJS6LWR0dKgMCeQ...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
6612060,30/Nov/2024:17:43:11 +0000,76.35.248.15,-,79H1PBZNDRF0VPEW,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",206,-,121396.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,s2sokHIzBQa+aVxkSffGunBCG+Iikop/WQnm66UG/Kj8cc...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
6612763,30/Nov/2024:21:46:56 +0000,76.35.248.15,-,8QGCAF8NSA7J1SB5,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",206,-,123771.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,9ROHnk1ze0lIX5KRN1tOiUbwS2NmQA6yhO0MmD4pLaCem5...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-
6612764,30/Nov/2024:21:46:58 +0000,76.35.248.15,-,CDEAKGS8WZZJFSRR,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",206,-,90596.0,...,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",-,OndDmDEbLXFs675ccd/SMs+Qv8OAR8cYNoh+ZIcDiwIWxl...,-,TLS_AES_128_GCM_SHA256,-,kyfromabove.s3.amazonaws.com,TLSv1.3,-,-

In [5]:
# check the columns
logs_filtered.columns

Index(['requestdatetime', 'remoteip', 'requester', 'requestid', 'operation',
       'key', 'request_uri', 'httpstatus', 'errorcode', 'bytessent',
       'objectsize', 'totaltime', 'turnaroundtime', 'referrer', 'useragent',
       'versionid', 'hostid', 'sigv', 'ciphersuite', 'authtype', 'endpoint',
       'tlsversion', 'accesspointarn', 'aclrequired'],
      dtype='object')

#### Drop more columns

After review, we can drop requestid, errorcode, versionid, hostid, sigv, ciphersuite, authtype, tlsversion, accesspointarn, aclrequired and of course, referrer.  These valuse don't mean anything regarding the questions I'm asking.

In [6]:
logs_filtered = logs_filtered.drop([
    'requestid', 'errorcode', 'versionid', 'hostid', 'sigv', 'ciphersuite', 'authtype',
    'tlsversion', 'accesspointarn', 'aclrequired', 'referrer'],
    axis=1)

print(logs_filtered.shape)
logs_filtered.head()

(1834294, 13)

,requestdatetime,remoteip,requester,operation,key,request_uri,httpstatus,bytessent,objectsize,totaltime,turnaroundtime,useragent,endpoint
0,01/Nov/2024:14:51:04 +0000,162.211.36.0,-,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,65536.0,90184411.0,134,132,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",kyfromabove.s3.amazonaws.com
1,01/Nov/2024:14:51:04 +0000,162.211.36.0,-,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,113170.0,90184411.0,131,90,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",kyfromabove.s3.amazonaws.com
2,01/Nov/2024:14:51:04 +0000,162.211.36.0,-,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,196.0,90184411.0,50,49,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",kyfromabove.s3.amazonaws.com
3,01/Nov/2024:14:51:05 +0000,162.211.36.0,-,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2024_Season1...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2024_S...",206,195.0,90184411.0,28,27,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",kyfromabove.s3.amazonaws.com
14,01/Nov/2024:15:11:51 +0000,65.34.46.11,-,REST.GET.OBJECT,imagery/obliques/Phase3/KY_KYAPED_2023_Season2...,"""GET /imagery/obliques/Phase3/KY_KYAPED_2023_S...",200,82086.0,82086.0,148,147,"""Mozilla/5.0 (Windows NT 10.0; Win64; x64) App...",kyfromabove.s3.amazonaws.com

#### More review, drop more columns

Looking at the dataframe above, I can see a few things that aren't really necessary.  We can filter "GET" from operation or request_uri.  I'll drop request_uri because it has a lot less characters and could probably save a little memory space.  Also, because of the earlier filter of referrer, the endpoint is likely the same for all rows.  The requester probably isn't necessary either, since it's requesting from a uri and not an actual user client.

Object size isn't too important, but I can leave it in for some easy calculations (eg., object size / bytes sent or object size / totaltime or turnaround time)

In [7]:
# drop request_uri, endpoint, and requestor
logs_filtered = logs_filtered.drop(['request_uri', 'endpoint', 'requester'], axis=1)
print(f'Dataframe Shape Values: {logs_filtered.shape}\n')
logs_filtered.columns

Dataframe Shape Values: (1834294, 10)

Index(['requestdatetime', 'remoteip', 'operation', 'key', 'httpstatus',
       'bytessent', 'objectsize', 'totaltime', 'turnaroundtime', 'useragent'],
      dtype='object')

___

## Data Cleaning and Preparation

In this section, I'm going to format the `requestdatetime` values so that it's just a day/month/year without a time stamp.



#### Create a new column

AWS S3 stores files as objects with bucket for location key as the name of the file.  This means a key could have several prefixes (analogous to folder or directory) on it's front end.  For example, for the key *imagery/obliques/Phase3/KY_KYAPED_2022_Season2_3IN/Bwd_2025_401340.tif* I eventually want to know the actual file name: *Bwd_2025_401340.tif*

In [ ]:
# format the requestdatetime column